#
# Copyright (c) Contributors to the Open 3D Engine Project.
# For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
#

set(FILES
    Include/PhysX/EditorColliderComponentRequestBus.h
    Include/PhysX/EditorJointBus.h
    Source/ComponentDescriptors.cpp
    Source/ComponentDescriptors.h
    Source/EditorComponentDescriptors.cpp
    Source/EditorComponentDescriptors.h
    Source/EditorRigidBodyComponent.cpp
    Source/EditorRigidBodyComponent.h
    Source/EditorColliderComponent.cpp
    Source/EditorColliderComponent.h
    Source/EditorShapeColliderComponent.cpp
    Source/EditorShapeColliderComponent.h
    Source/EditorForceRegionComponent.cpp
    Source/EditorForceRegionComponent.h
    Source/EditorBallJointComponent.cpp
    Source/EditorBallJointComponent.h
    Source/EditorFixedJointComponent.cpp
    Source/EditorFixedJointComponent.h
    Source/EditorHingeJointComponent.cpp
    Source/EditorHingeJointComponent.h
    Source/EditorHeightfieldColliderComponent.cpp
    Source/EditorHeightfieldColliderComponent.h
    Source/EditorJointComponent.cpp
    Source/EditorJointComponent.h
    Source/Pipeline/MeshExporter.cpp
    Source/Pipeline/MeshExporter.h
    Source/Pipeline/MeshGroup.cpp
    Source/Pipeline/MeshGroup.h
    Source/Pipeline/MeshBehavior.cpp
    Source/Pipeline/MeshBehavior.h
    Source/Pipeline/PrimitiveShapeFitter/PrimitiveShapeFitter.cpp
    Source/Pipeline/PrimitiveShapeFitter/PrimitiveShapeFitter.h
    Source/Pipeline/PrimitiveShapeFitter/AbstractShapeParameterization.cpp
    Source/Pipeline/PrimitiveShapeFitter/AbstractShapeParameterization.h
    Source/Pipeline/PrimitiveShapeFitter/Utils.cpp
    Source/Pipeline/PrimitiveShapeFitter/Utils.h
    Source/PhysXCharacters/Components/EditorCharacterControllerComponent.cpp
    Source/PhysXCharacters/Components/EditorCharacterControllerComponent.h
    Source/PhysXCharacters/Components/EditorCharacterGameplayComponent.cpp
    Source/PhysXCharacters/Components/EditorCharacterGameplayComponent.h
    Editor/ConfigurationWidget.h
    Editor/ConfigurationWidget.cpp
    Editor/EditorWindow.h
    Editor/EditorWindow.cpp
    Editor/EditorWindow.ui
    Editor/SettingsWidget.h
    Editor/SettingsWidget.cpp
    Editor/CollisionLayersWidget.h
    Editor/CollisionLayersWidget.cpp
    Editor/CollisionLayerWidget.h
    Editor/CollisionLayerWidget.cpp
    Editor/CollisionGroupWidget.h
    Editor/CollisionGroupWidget.cpp
    Editor/CollisionGroupsWidget.h
    Editor/CollisionGroupsWidget.cpp
    Editor/CollisionFilteringWidget.h
    Editor/CollisionFilteringWidget.cpp
    Editor/PropertyTypes.h
    Editor/PropertyTypes.cpp
    Editor/MaterialIdWidget.h
    Editor/MaterialIdWidget.cpp
    Editor/EditorClassConverters.cpp
    Editor/EditorClassConverters.h
    Editor/PvdWidget.h
    Editor/PvdWidget.cpp
    Editor/DocumentationLinkWidget.h
    Editor/DocumentationLinkWidget.cpp
    Editor/InertiaPropertyHandler.h
    Editor/InertiaPropertyHandler.cpp
    Editor/ConfigStringLineEditCtrl.h
    Editor/ConfigStringLineEditCtrl.cpp
    Editor/UniqueStringContainer.h
    Editor/UniqueStringContainer.cpp
    Editor/ComboBoxEditButtonPair.h
    Editor/ComboBoxEditButtonPair.cpp
    Editor/ColliderComponentMode.h
    Editor/ColliderComponentMode.cpp
    Editor/ColliderOffsetMode.h
    Editor/ColliderOffsetMode.cpp
    Editor/ColliderBoxMode.h
    Editor/ColliderBoxMode.cpp
    Editor/ColliderRotationMode.h
    Editor/ColliderRotationMode.cpp
    Editor/ColliderSphereMode.h
    Editor/ColliderSphereMode.cpp
    Editor/ColliderCapsuleMode.h
    Editor/ColliderCapsuleMode.cpp
    Editor/ColliderAssetScaleMode.h
    Editor/ColliderAssetScaleMode.cpp
    Editor/DebugDraw.cpp
    Editor/DebugDraw.h
    Editor/PolygonPrismMeshUtils.cpp
    Editor/PolygonPrismMeshUtils.h
    Editor/EditorJointCommon.h
    Editor/EditorJointConfiguration.cpp
    Editor/EditorJointConfiguration.h
    Editor/EditorViewportEntityPicker.cpp
    Editor/EditorViewportEntityPicker.h

    Editor/Source/Components/EditorSystemComponent.h
    Editor/Source/Components/EditorSystemComponent.cpp
    Editor/Source/ComponentModes/Joints/JointsComponentMode.h
    Editor/Source/ComponentModes/Joints/JointsComponentMode.cpp
    Editor/Source/ComponentModes/Joints/JointsComponentModeCommon.h
    Editor/Source/ComponentModes/Joints/JointsComponentModeCommon.cpp
    Editor/Source/ComponentModes/PhysXSubComponentModeBase.h
    Editor/Source/ComponentModes/Joints/JointsSubComponentModeAngleCone.h
    Editor/Source/ComponentModes/Joints/JointsSubComponentModeAngleCone.cpp
    Editor/Source/ComponentModes/Joints/JointsSubComponentModeAnglePair.h
    Editor/Source/ComponentModes/Joints/JointsSubComponentModeAnglePair.cpp
    Editor/Source/ComponentModes/Joints/JointsSubComponentModeLinearFloat.h
    Editor/Source/ComponentModes/Joints/JointsSubComponentModeLinearFloat.cpp
    Editor/Source/ComponentModes/Joints/JointsSubComponentModeRotation.h
    Editor/Source/ComponentModes/Joints/JointsSubComponentModeRotation.cpp
    Editor/Source/ComponentModes/Joints/JointsSubComponentModeSnap.h
    Editor/Source/ComponentModes/Joints/JointsSubComponentModeSnap.cpp
    Editor/Source/ComponentModes/Joints/JointsSubComponentModeSnapPosition.h
    Editor/Source/ComponentModes/Joints/JointsSubComponentModeSnapPosition.cpp
    Editor/Source/ComponentModes/Joints/JointsSubComponentModeSnapRotation.h
    Editor/Source/ComponentModes/Joints/JointsSubComponentModeSnapRotation.cpp
    Editor/Source/ComponentModes/Joints/JointsSubComponentModeTranslate.h
    Editor/Source/ComponentModes/Joints/JointsSubComponentModeTranslate.cpp
    Editor/Source/Configuration/PhysXEditorSettingsRegistryManager.h
    Editor/Source/Configuration/PhysXEditorSettingsRegistryManager.cpp

    Editor/Source/PhysXMaterial/PhysXMaterialSourceData.cpp
    Editor/Source/PhysXMaterial/PhysXMaterialSourceData.h
    Editor/Source/PhysXMaterial/PhysXMaterialTypeSourceData.cpp
    Editor/Source/PhysXMaterial/PhysXMaterialTypeSourceData.h
    Editor/Source/PhysXMaterial/PhysXMaterialUtils.cpp
    Editor/Source/PhysXMaterial/PhysXMaterialUtils.h
    Editor/Source/PhysXMaterial/Serializer/PhysXMaterialPropertyValueSerializer.cpp
    Editor/Source/PhysXMaterial/Serializer/PhysXMaterialPropertyValueSerializer.h
    Editor/Source/PhysXMaterial/Serializer/PhysXMaterialPropertySerializer.cpp
    Editor/Source/PhysXMaterial/Serializer/PhysXMaterialPropertySerializer.h
    Editor/Source/PhysXMaterial/Serializer/PhysXMaterialPropertyGroupSerializer.cpp
    Editor/Source/PhysXMaterial/Serializer/PhysXMaterialPropertyGroupSerializer.h
    
    Editor/Source/PhysXMaterialBuilder/PhysXMaterialBuilder.cpp
    Editor/Source/PhysXMaterialBuilder/PhysXMaterialBuilder.h
    Editor/Source/PhysXMaterialBuilder/PhysXMaterialBuilderComponent.cpp
    Editor/Source/PhysXMaterialBuilder/PhysXMaterialBuilderComponent.h
    
    Editor/Source/MaterialEditor/PhysXMaterialEditorSystemComponent.cpp
    Editor/Source/MaterialEditor/PhysXMaterialEditorSystemComponent.h
    Editor/Source/MaterialEditor/Document/MaterialDocumentRequestBus.h
    Editor/Source/MaterialEditor/Document/MaterialDocument.cpp
    Editor/Source/MaterialEditor/Document/MaterialDocument.h
    Editor/Source/MaterialEditor/Viewport/MaterialViewportWidget.cpp
    Editor/Source/MaterialEditor/Viewport/MaterialViewportWidget.h
    Editor/Source/MaterialEditor/Viewport/MaterialViewportWidget.ui
    Editor/Source/MaterialEditor/Window/MaterialEditorWindowSettings.h
    Editor/Source/MaterialEditor/Window/MaterialEditorWindow.h
    Editor/Source/MaterialEditor/Window/MaterialEditorWindow.cpp
    Editor/Source/MaterialEditor/Window/MaterialEditorWindowSettings.cpp
    Editor/Source/MaterialEditor/Window/MaterialEditor.qrc
    Editor/Source/MaterialEditor/Window/MaterialEditor.qss
    Editor/Source/MaterialEditor/Window/SettingsDialog/MaterialEditorSettingsDialog.cpp
    Editor/Source/MaterialEditor/Window/SettingsDialog/MaterialEditorSettingsDialog.h
    Editor/Source/MaterialEditor/Window/SettingsDialog/MaterialEditorSettingsWidget.cpp
    Editor/Source/MaterialEditor/Window/SettingsDialog/MaterialEditorSettingsWidget.h
    Editor/Source/MaterialEditor/Window/CreateMaterialDialog/CreateMaterialDialog.cpp
    Editor/Source/MaterialEditor/Window/CreateMaterialDialog/CreateMaterialDialog.h
    Editor/Source/MaterialEditor/Window/CreateMaterialDialog/CreateMaterialDialog.ui
    Editor/Source/MaterialEditor/Window/MaterialInspector/MaterialInspector.h
    Editor/Source/MaterialEditor/Window/MaterialInspector/MaterialInspector.cpp
)
