name: o3de
version: '0.0.0.0'
summary: O3DE Engine
description: |
  O3DE Engine
confinement: classic
base: core22

parts:
  test-o3de:
    plugin: dump
    source: ./O3DE
    source-type: local
    stage-packages:
     - clang
     - ninja-build
     - libatomic1
     - libfreetype6
     - libpng16-16
     - libgl1
     - libxcb-icccm4
     - libxcb-image0
     - libxcb-keysyms1
     - libxcb-randr0
     - libxcb-render-util0
     - libxcb-render0
     - libxcb-shape0
     - libxcb-xinerama0
     - libxcb-xinput0
     - libxcb-xkb1
     - libxkbcommon-x11-0
     - libxkbcommon0
     - libpcre2-16-0
     - libopengl0
     - libice6
     - libsm6
     - libcurl4
     - libfontconfig1
    stage-snaps:
     - cmake

layout:
  /etc/o3de/22.10/downloaded_packages:
    bind: $SNAP/0.0.0.0/python/downloaded_packages
  /etc/o3de/22.10/runtime:
    bind: $SNAP/0.0.0.0/python/runtime

apps:
  o3de:
    command: 0.0.0.0/bin/Linux/profile/Default/o3de
    environment:
      LD_LIBRARY_PATH: $SNAP/0.0.0.0/bin/Linux/profile/Default:$LD_LIBRARY_PATH
      DISABLE_WAYLAND: 1
  editor:
    command: 0.0.0.0/bin/Linux/profile/Default/Editor
    environment:
      LD_LIBRARY_PATH: $SNAP/0.0.0.0/bin/Linux/profile/Default:$LD_LIBRARY_PATH
      DISABLE_WAYLAND: 1
  assetprocessor:
    command: 0.0.0.0/bin/Linux/profile/Default/AssetProcessor
    environment:
      LD_LIBRARY_PATH: $SNAP/0.0.0.0/bin/Linux/profile/Default:$LD_LIBRARY_PATH
      DISABLE_WAYLAND: 1
    
